name: Github-action-demo

on:
  pull_request:
    branches:
      - master
    types:
      - closed
#   push:
#     branches: [ master ]
jobs:
  build:
    environment:
      name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER_NAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build & push the Docker image
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USER_NAME }}
        run: |
          export VERSION=$(cat service.yaml)
          export CF_IMAGE=quay.io/$QUAY_USERNAME/${{ github.event.repository.name }}:$VERSION
          echo "CF_IMAGE=$CF_IMAGE" >> $GITHUB_ENV
          docker build . --file Dockerfile --build-arg COLOR=$VERSION --tag $CF_IMAGE && docker push $CF_IMAGE
      
      - name: report image
        with:
          # Name of runtime to implement the enrichment
#           CF_HOST: 'https://eti-demo.pipeline-team.cf-cd.com'
#           CF_RUNTIME_NAME: 'prod-eks-26-10-2022'
#           CF_RUNTIME_NAME: 'codefresh-hosted'
#           CF_PLATFORM_URL: 'https://g.codefresh.io'
          CF_RUNTIME_NAME: 'sec-eks-02-11-2022'
          CF_PLATFORM_URL: 'https://sec.codefresh.io'

          # Codefresh API key !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
          CF_API_KEY: ${{secrets.CF_API_KEY_SEC}}

          # Name of Container registry integration
          CF_CONTAINER_REGISTRY_INTEGRATION: 'quay-test2'

#           # Name of Jira integration
#           CF_JIRA_INTEGRATION: 'jira-demo2'

          CF_ISSUE_TRACKING_INTEGRATION: 'jira'

          # Image path to enrich
          CF_IMAGE: ${{env.CF_IMAGE}}
#           # Image path to enrich
#           CF_IMAGE: gcr.io/heptio-images/ks-guestbook-demo:0.1
          
          # GitHub Access token !! Committing a plain text token is a security risk. We highly recommend using an encrypted secrets. !!
          # Documentation - https://docs.github.com/en/actions/security-guides/encrypted-secrets
#           CF_GITHUB_TOKEN: ${{secrets.PAT}}

          # Jira project filter
          CF_JIRA_PROJECT_PREFIX: 'TES'

          # String starting with the issue ID to associate with image
          CF_JIRA_MESSAGE: "${{ github.event.pull_request.head.ref }}"
#           CF_JIRA_MESSAGE: "CR-12345"
#           CF_GIT_PROVIDER: "github"
          CF_GIT_BRANCH: "${{ github.event.pull_request.head.ref }}"

        uses: codefresh-io/codefresh-report-image@latest

#         uses: eti-codefresh/codefresh-report-image@git-provider-2

      #- name: Report image
       # with:
        #  CF_IMAGE: ${{ env.CF_IMAGE }}
         # CF_HOST: "https://mr-5f04515c6f790a046303eb5a-d0a662e.cf-cd.com"
          #CF_API_KEY: ${{ secrets.CF_API_KEY }}
       #   CF_CONTAINER_REGISTRY_INTEGRATION: "docker"
        #  CF_JIRA_INTEGRATION: "jira"
         # CF_GITHUB_TOKEN: ${{ secrets.PAT }}
        #  CF_JIRA_MESSAGE: "${{ github.event.head_commit.message }}"
        #  CF_JIRA_PROJECT_PREFIX: "CR"
       # uses: codefresh-io/codefresh-report-image@latest
      - name: Checkout csdp-salesdemo_applications
        uses: actions/checkout@v3
        with:
          repository: eti-codefresh/canary-rollout # change to real repo
          path: .
      - name: Update application version
        run: |
          IMAGE=${{ env.CF_IMAGE }} yq -i '.spec.template.spec.containers.[0].image = strenv(IMAGE)' canary-rollout.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-application-version
          delete-branch: true
          title: 'Update application version'
          body: |
            Update deployment version
            - Updated new version for hello-world application
          labels: |
            automated pr
          draft: false

